use std::{collections::HashSet, ops::Deref};

use dbt_common::{
    ErrorCode, FsResult, create_debug_span_with_parent, create_info_span_with_parent, fs_err,
};
use dbt_tracing::TelemetryAttributes;
use tracing::{Span, span::Id as SpanId};

/// A subset of severity level for spans, since other severity levels are not used here.
///
/// Determines visibility in tracing output:
/// - `Info`: Shown in normal operation (e.g., `NodeProcessed` with `last_phase=Run`)
/// - `Debug`: Shown only with debug logging (e.g., `NodeEvaluated` for intermediate phases)
#[derive(Debug, Clone, Copy, Hash, PartialEq, Eq)]
pub enum SpanLevel {
    Info,
    Debug,
}

impl From<SpanLevel> for tracing::Level {
    fn from(level: SpanLevel) -> Self {
        match level {
            SpanLevel::Info => tracing::Level::INFO,
            SpanLevel::Debug => tracing::Level::DEBUG,
        }
    }
}

/// Callback to handle task span close at task level.
pub type TaskSpanOnClose<R> = Box<dyn FnOnce(&Span, &R) + Send + Sync>;
/// Callback to handle task span skip at task level.
pub type TaskSpanOnSkip<S> = Box<dyn FnOnce(&Span, &S) + Send + Sync>;
/// Callback to handle parent span close at parent level.
pub type ParentSpanOnClose = Box<dyn FnOnce(&Span) + Send + Sync>;
/// Callback to handle task span close at all task ancestor levels.
pub type ParentTaskSpanOnClose<R> = Box<dyn Fn(&Span, &Span, &R) -> bool + Send + Sync>;
/// Callback to handle task span skip at all task ancestor levels.
pub type ParentTaskSpanOnSkip<S> = Box<dyn Fn(&Span, &Span, &S) -> bool + Send + Sync>;

/// Builder for parent span attributes and lifecycle callbacks.
///
/// Encapsulates lazy creation of span metadata, invoked only when span is first created.
pub struct ParentSpanBuilder<R, S> {
    attributes: TelemetryAttributes,
    on_close: Option<ParentSpanOnClose>,
    on_task_close: Option<ParentTaskSpanOnClose<R>>,
    on_task_skip: Option<ParentTaskSpanOnSkip<S>>,
}

impl<R, S> ParentSpanBuilder<R, S> {
    /// Creates a new parent span builder.
    ///
    /// # Arguments
    /// - `attributes`: Telemetry attributes for the span
    /// - `on_close`: Callback when parent span closes (no more children)
    /// - `on_task_close`: Callback when any descendant task completes
    /// - `on_task_skip`: Callback when any descendant task is skipped
    pub fn new(
        attributes: TelemetryAttributes,
        on_close: Option<ParentSpanOnClose>,
        on_task_close: Option<ParentTaskSpanOnClose<R>>,
        on_task_skip: Option<ParentTaskSpanOnSkip<S>>,
    ) -> Self {
        Self {
            attributes,
            on_close,
            on_task_close,
            on_task_skip,
        }
    }
}

/// Newtype for span key used in span manager to identify registered parent spans.
/// Unlike SpanId, which are assigned at span creation time (a counter basically),
/// span keys are are generated by stable naming scheme
#[derive(Debug, Clone, Hash, PartialEq, Eq)]
pub struct SpanKey(String);

impl From<&str> for SpanKey {
    fn from(s: &str) -> Self {
        SpanKey(s.to_string())
    }
}

impl From<String> for SpanKey {
    fn from(s: String) -> Self {
        SpanKey(s)
    }
}

impl Deref for SpanKey {
    type Target = String;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl SpanKey {
    fn as_str(&self) -> &str {
        &self.0
    }
}

/// A reference to a parent span by level and key, looked up in the span manager's
/// pre-registered builders.
#[derive(Debug, Clone, Hash, PartialEq, Eq)]
pub struct ParentSpanRef {
    level: SpanLevel,
    span_key: SpanKey,
}

impl ParentSpanRef {
    pub fn new(level: SpanLevel, span_key: SpanKey) -> Self {
        Self { level, span_key }
    }
}

/// Metadata and builder for a registered parent span.
struct RegisteredParentSpan<R, S> {
    /// Optional parent span reference. If None, uses span manager's current span as parent.
    parent_ref: Option<ParentSpanRef>,
    /// Builder function that creates the ParentSpanBuilder when called.
    builder_fn: Box<dyn FnOnce() -> ParentSpanBuilder<R, S> + Send + Sync>,
}

/// A request to create a task span.
struct TaskSpanRequest<R, S> {
    level: SpanLevel,
    attributes: TelemetryAttributes,
    on_close: Option<TaskSpanOnClose<R>>,
    on_skip: Option<TaskSpanOnSkip<S>>,
}

impl<R, S> TaskSpanRequest<R, S> {
    fn new(
        level: SpanLevel,
        attributes: TelemetryAttributes,
        on_close: Option<TaskSpanOnClose<R>>,
        on_skip: Option<TaskSpanOnSkip<S>>,
    ) -> Self {
        Self {
            level,
            attributes,
            on_close,
            on_skip,
        }
    }

    /// Creates a managed task span from this request under the given parent span.
    /// The related_ids are the innermost span IDs of each related span chain.
    fn into_managed(self, parent_id: SpanId, related_ids: Vec<SpanId>) -> ManagedTaskSpan<R, S> {
        let span = match self.level {
            SpanLevel::Info => {
                create_info_span_with_parent(Some(parent_id.clone()), self.attributes)
            }
            SpanLevel::Debug => {
                create_debug_span_with_parent(Some(parent_id.clone()), self.attributes)
            }
        };

        // Establish follows_from relationships with all related spans
        for related_id in &related_ids {
            span.follows_from(related_id);
        }

        let span_id = span.id().expect("Span must have ID");
        ManagedTaskSpan {
            span,
            span_id,
            managed_parent_id: parent_id,
            related_ids,
            on_close: self.on_close,
            on_skip: self.on_skip,
        }
    }
}

/// Request to generate a span tree for a task, including parent and related spans.
///
/// Contains only span keys that reference pre-registered builders in the span manager.
/// Spans are lazily created on first request and then reused for subsequent requests.
pub struct SpanTreeRequest<R, S> {
    /// Holds parent span references from inner most to outer most.
    parent_span: Option<ParentSpanRef>,

    /// Holds related span ref keys.
    /// Task span will establish follows_from relationship with them.
    related_spans: HashSet<ParentSpanRef>,

    /// An optional task span request. If None, the task should use
    /// the current span.
    task_span: Option<TaskSpanRequest<R, S>>,
}

/// Builder for constructing span tree requests.
///
/// # Usage
/// ```ignore
/// SpanTreeRequest::builder(level, attributes, on_close, on_skip)
///     .with_parent(level, "TestGroup:model:x")
///     .add_related_span(level, "NodeProcessed:test1")
///     .build()
/// ```
pub struct SpanTreeRequestBuilder<R, S> {
    /// Holds parent span references from inner most to outer most.
    parent_span: Option<ParentSpanRef>,

    /// Holds related span ref keys.
    /// Task span will establish follows_from relationship with them.
    related_spans: HashSet<ParentSpanRef>,

    /// An optional task span request. If None, the task should use
    /// the current span.
    task_span: Option<TaskSpanRequest<R, S>>,
}

impl<R, S> SpanTreeRequestBuilder<R, S> {
    /// Adds a parent span
    ///
    /// # Arguments
    /// - `level`: Severity level of the span
    /// - `span_key`: Unique identifier referencing a pre-registered span builder (e.g., `"PhaseExecuted::Render"`)
    ///
    /// # Warning
    /// `get_task_span` called based on this request will error out if the span_key was not pre-registered in the span manager.
    /// Make sure the correct keys are used. See `SpanManager::new_for_tasks` for pre-registered keys.
    ///
    /// # Panics
    /// Panics if called multiple times on the same builder.
    pub fn with_parent(&mut self, level: SpanLevel, span_key: impl Into<SpanKey>) -> &mut Self {
        debug_assert!(
            self.parent_span.is_none(),
            "with_parent called multiple times on SpanTreeRequestBuilder"
        );
        self.parent_span = Some(ParentSpanRef::new(level, span_key.into()));
        self
    }

    /// Adds related span. Task establishes `follows_from` relationship with it.
    ///
    /// # Arguments
    /// - `level`: Severity level of the span
    /// - `span_key`: Unique identifier referencing a pre-registered span builder (e.g., `"NodeProcessed::model.x"`)
    ///
    /// # Warning
    /// `get_task_span` called based on this request will error out if the span_key was not pre-registered in the span manager.
    /// Make sure the correct keys are used. See `SpanManager::new_for_tasks` for pre-registered keys.
    ///
    /// # Panics
    /// Panics if called multiple times with the same span_key on the same builder.
    pub fn add_related_span(&mut self, level: SpanLevel, span_key: &'_ str) -> &mut Self {
        let span = ParentSpanRef::new(level, span_key.into());

        debug_assert!(
            !self.related_spans.contains(&span),
            "add_related_span called with duplicate span_key: {}",
            span_key
        );

        self.related_spans.insert(span);
        self
    }

    /// Finalizes and returns the span tree request.
    pub fn build(self) -> SpanTreeRequest<R, S> {
        SpanTreeRequest::<R, S> {
            parent_span: self.parent_span,
            related_spans: self.related_spans,
            task_span: self.task_span,
        }
    }
}

impl<R, S> SpanTreeRequest<R, S> {
    /// Creates a no-op request for tasks to use the current span without creating new spans.
    pub fn use_current() -> Self {
        Self {
            parent_span: None,
            related_spans: HashSet::new(),
            task_span: None,
        }
    }

    /// Creates a builder for a span tree request with a task span.
    ///
    /// # Arguments
    /// - `level`: Severity level for the task span
    /// - `attributes`: Telemetry attributes for the task span
    /// - `on_close`: Callback invoked when task completes successfully
    /// - `on_skip`: Callback invoked when task is skipped
    pub fn builder(
        level: SpanLevel,
        attributes: TelemetryAttributes,
        on_close: Option<TaskSpanOnClose<R>>,
        on_skip: Option<TaskSpanOnSkip<S>>,
    ) -> SpanTreeRequestBuilder<R, S> {
        SpanTreeRequestBuilder {
            parent_span: None,
            related_spans: HashSet::new(),
            task_span: Some(TaskSpanRequest::new(level, attributes, on_close, on_skip)),
        }
    }
}

/// Represents a managed tracing parent span within span manager.
///
/// This is used to hold on to a sub-tree of spans under which all
/// task spans are nested, hence we track children remaining instead
/// of relying on tracing registry to automatically close these spans
/// when all children are done and they go out of scope.
struct ManagedParentSpan<R, S> {
    span: Span,
    // Save to avoid existence checks on every child addition/removal
    span_id: SpanId,
    managed_parent_id: Option<SpanId>,
    #[allow(dead_code)] // Used only in debug_assertions
    span_key: SpanKey,
    children: HashSet<SpanId>,
    on_close: Option<ParentSpanOnClose>,
    on_task_close: Option<ParentTaskSpanOnClose<R>>,
    on_task_skip: Option<ParentTaskSpanOnSkip<S>>,
}

impl<R, S> ManagedParentSpan<R, S> {
    /// Creates a new managed parent span.
    fn new(
        span: Span,
        managed_parent_id: Option<SpanId>,
        span_key: SpanKey,
        on_close: Option<ParentSpanOnClose>,
        on_task_close: Option<ParentTaskSpanOnClose<R>>,
        on_task_skip: Option<ParentTaskSpanOnSkip<S>>,
    ) -> Self {
        let span_id = span.id().expect("Span must have ID");

        Self {
            span,
            span_id,
            managed_parent_id,
            span_key,
            children: HashSet::new(),
            on_close,
            on_task_close,
            on_task_skip,
        }
    }
}

/// Holds a reference to a managed task span within span manager,
/// allowing to invoke the on close callback when the task is done.
struct ManagedTaskSpan<R, S> {
    span: Span,
    // Save to avoid existence checks on every child addition/removal
    span_id: SpanId,
    /// ID of the managed parent span under which this task span was created.
    /// This span will be notified when the task span closes or is skipped.
    managed_parent_id: SpanId,
    /// IDs of related spans (innermost span from each related chain).
    /// These spans receive follows_from relationship and are notified on task close/skip.
    related_ids: Vec<SpanId>,
    on_close: Option<TaskSpanOnClose<R>>,
    on_skip: Option<TaskSpanOnSkip<S>>,
}

/// Manages tracing spans for task execution across multiple phases.
///
/// # Overview
/// Coordinates span creation, reuse, and lifecycle for dbt node execution. Spans are lazily
/// created on first request and shared across phases, enabling hierarchical tracing for
/// nodes of all types and their execution phases.
///
/// # Span Hierarchy
///
/// ## Main task chain
/// ```text
/// [visitor's current span]
///   └─ PhaseExecuted (phase=Render) [Info]
///       ├─ NodeEvaluated (phase=Render, unique_id=model.x) [Debug]
///       │  └─ follows_from ── NodeProcessed (unique_id=model.x, last_phase=Run) [Info]
///       ├─ NodeEvaluated (phase=Render, unique_id=test.y) [Debug]
///       │  └─ follows_from ── NodeProcessed (unique_id=test.y, last_phase=Run) [Info]
///       └─ ...
///   └─ ...
///   └─ PhaseExecuted (phase=Run) [Info]
///       ├─ NodeEvaluated (phase=Run, unique_id=model.x) [Debug]
///       │  └─ follows_from ── NodeProcessed (unique_id=model.x, last_phase=Run) [Info]
///       ├─ NodeEvaluated (phase=Run, unique_id=test.y) [Debug]
///       │  └─ follows_from ── NodeProcessed (unique_id=test.y, last_phase=Run) [Info]
///       └─ ...
/// ```
///
/// ## Related task chain (used for aggregage node result reporting)
/// ```text
/// [visitor's current span]
///   └─ TuiAllProcessingNodesGroup (single span for all nodes)
///       ├─ NodeProcessed (unique_id=model.x, last_phase=Run) [Info]
///       ├─ NodeProcessed (unique_id=test.y, last_phase=Run) [Info]
///       └─ ...
/// ```
///
/// # Illustration of the lifecycle across multiple tasks
///
/// **T1**: First node (model:x) hits Render phase
/// ```text
/// Request: PhaseExecuted(phase=Render) → Created
///          NodeProcessed(unique_id=model:x, last_phase=Run) → Created (related span)
///          NodeEvaluated(phase=Render, unique_id=model:x) → Created (task span)
///            └─ follows_from NodeProcessed
/// ```
///
/// **T2**: Second node (test:y) hits Render phase
/// ```text
/// Request: PhaseExecuted(phase=Render) → Already exists, reused
///          NodeProcessed(unique_id=test:y, last_phase=Run) → Created (related span)
///          NodeEvaluated(phase=Render, unique_id=test:y) → Created (task span)
///            └─ follows_from NodeProcessed
/// ```
///
/// **T3**: First node (model:x) hits Run phase
/// ```text
/// Request: PhaseExecuted(phase=Run) → Created
///          NodeProcessed(unique_id=model:x, last_phase=Run) → Already exists, reused
///          NodeEvaluated(phase=Run, unique_id=model:x) → Created (task span)
///            └─ follows_from NodeProcessed
/// ```
///
/// **T4**: Last phase (Run) completes for model:x, triggering parent closure
/// ```text
/// NodeEvaluated(phase=Run, unique_id=model:x) → Closes
/// NodeProcessed(unique_id=model:x, last_phase=Run) → No children remain, closes
/// PhaseExecuted(phase=Run) → Still has other children (test:y), remains open
/// ```
///
/// # Type Parameters
/// - `R`: Result type passed to `on_close` callbacks when tasks complete
/// - `S`: Skip reason type passed to `on_skip` callbacks when tasks are skipped
pub struct SpanManager<R, S> {
    /// The SpanId of the current span when the manager was created.
    /// This is the root span under which all managed spans are nested.
    span_manager_cur_span_id: SpanId,
    /// Task spans keyed by their SpanId.
    ///
    /// Note: Even tohugh `tracing` re-uses span Id's, it is safe to use them here
    /// becuase the ManagedTaskSpan holds a reference to the Span, preventing the
    /// SpanId from being recycled until the entry is removed.
    task_spans: scc::HashMap<SpanId, ManagedTaskSpan<R, S>>,
    /// Managed parent/related spans keyed by their SpanId.
    ///
    /// Note: Even tohugh `tracing` re-uses span Id's, it is safe to use them here
    /// becuase the ManagedParentSpan holds a reference to the Span, preventing the
    /// SpanId from being recycled until the entry is removed.
    parent_spans: scc::HashMap<SpanId, ManagedParentSpan<R, S>>,
    parent_span_key_to_span_id: scc::HashMap<SpanKey, SpanId>,
    /// Pre-registered parent span metadata and builders, keyed by span key.
    /// Contains parent chain information for automatic hierarchy expansion.
    /// Must be populated before any task spans are created.
    registered_builders: scc::HashMap<SpanKey, RegisteredParentSpan<R, S>>,
}

impl<R, S> SpanManager<R, S> {
    /// Creates a new span manager rooted at the current tracing span.
    ///
    /// This is a lower-level constructor. Most callers should use `SpanManager::new_for_tasks`
    /// which also populates the span manager with parent span builders.
    ///
    /// # Panics
    /// Panics if called outside of a tracing span context.
    pub fn new_empty() -> Self {
        // Create a managed span for the current span.
        let cur_span = Span::current();
        let span_manager_cur_span_id = cur_span
            .id()
            .expect("Span manager must be created within a span");

        let cur_as_managed = ManagedParentSpan::<R, S>::new(
            Span::current(),
            None,
            "".into(),
            None,
            // The following will indicate that span manager span should never "unmanage" the root
            Some(Box::new(|_, _, _| false)),
            Some(Box::new(|_, _, _| false)),
        );

        Self {
            span_manager_cur_span_id: span_manager_cur_span_id.clone(),
            task_spans: scc::HashMap::new(),
            parent_spans: scc::HashMap::from_iter([(span_manager_cur_span_id, cur_as_managed)]),
            parent_span_key_to_span_id: scc::HashMap::new(),
            registered_builders: scc::HashMap::new(),
        }
    }
}

impl<R, S> SpanManager<R, S> {
    /// Registers a parent span builder with the given key and optional parent.
    ///
    /// This must be called before any task spans request this parent span.
    /// When this span is requested, its parent will be recursively created if needed.
    ///
    /// # Arguments
    /// - `span_key`: Unique identifier for this parent span builder
    /// - `parent_ref`: Optional parent span reference. If None, uses current span as parent.
    /// - `builder_fn`: Closure that creates the ParentSpanBuilder when called
    ///
    /// # Returns
    /// - `Ok(())`: Builder was registered successfully
    /// - `Err`: A builder with the same key was already registered
    pub fn register_parent_span_builder(
        &self,
        span_key: String,
        parent_ref: Option<ParentSpanRef>,
        builder_fn: Box<dyn FnOnce() -> ParentSpanBuilder<R, S> + Send + Sync>,
    ) -> FsResult<()> {
        self.registered_builders
            .insert_sync(
                span_key.as_str().into(),
                RegisteredParentSpan {
                    parent_ref,
                    builder_fn,
                },
            )
            .map_err(|_| {
                fs_err!(
                    ErrorCode::Unexpected,
                    "Parent span builder already registered for key: {}",
                    span_key
                )
            })?;
        Ok(())
    }

    /// Ensures a parent span exists, creating it and its ancestors recursively if needed.
    ///
    /// Searches for existing span among children of the appropriate parent. If found, returns it.
    /// If not found, recursively ensures the span's parent exists, then creates this span.
    ///
    /// # Arguments
    /// - `span_ref`: Reference to the span to ensure exists
    ///
    /// # Returns
    /// - `Ok(SpanId)`: ID of the existing or newly created span
    /// - `Err`: If span_key was not registered
    fn ensure_span_exists(&self, span_ref: ParentSpanRef) -> FsResult<SpanId> {
        // Check if span already created & managed by span manager
        if let Some(already_managed_span_id) = self
            .parent_span_key_to_span_id
            .read_sync(&span_ref.span_key, |_, span_id| span_id.clone())
        {
            return Ok(already_managed_span_id);
        }

        // Look up the registered metadata (without consuming builder yet) for the expected grandparent
        let parent_ref_opt = self
            .registered_builders
            .read_sync(&span_ref.span_key, |_, registered| registered.parent_ref.clone())
            .ok_or_else(|| {
                fs_err!(
                    ErrorCode::Unexpected,
                    "Parent span builder not found for key: {}. Ensure populate_span_manager was called before task execution.",
                    span_ref.span_key.as_str()
                )
            })?;

        // Determine the parent under which this span should be created
        let parent_id = if let Some(parent_ref) = parent_ref_opt {
            // Recursively ensure parent exists
            self.ensure_span_exists(parent_ref)?
        } else {
            // No parent specified, use span manager's current span
            self.span_manager_cur_span_id.clone()
        };

        #[cfg(debug_assertions)]
        {
            // This span should not exist among parent's children, otherwise
            // we should have found it at the start of this function.
            // We have to read span_key into the vector first, to avoid deadlocks,
            // we can't just read and check in the same lock.
            let child_ids: Vec<SpanId> = self
                .parent_spans
                .get_sync(&parent_id)
                .expect("Parent span must exist")
                .children
                .iter()
                .cloned()
                .collect();

            for child_id in child_ids {
                if let Some(mspan) = self.parent_spans.get_sync(&child_id)
                    && mspan.span_key == span_ref.span_key
                {
                    panic!(
                        "Span with key {} already exists under parent {:?}, but not among managed spans",
                        span_ref.span_key.as_str(),
                        parent_id
                    );
                }
            }
        }

        // Span doesn't exist, create it
        self.create_managed_parent_span(parent_id, span_ref)
    }

    /// Creates a ManagedParentSpan by looking up and calling the registered builder.
    fn create_managed_parent_span(
        &self,
        managed_parent_id: SpanId,
        parent_span_ref: ParentSpanRef,
    ) -> FsResult<SpanId> {
        // Look up and remove the registered span (contains builder and metadata)
        let registered_span = self
            .registered_builders
            .remove_sync(&parent_span_ref.span_key)
            .ok_or_else(|| {
                fs_err!(
                    ErrorCode::Unexpected,
                    "Parent span builder not found for key: {}. Ensure populate_span_manager was called before task execution.",
                    parent_span_ref.span_key.as_str()
                )
            })?
            .1;

        // Call the builder to get attributes and callbacks
        let builder = (registered_span.builder_fn)();
        let ParentSpanBuilder {
            attributes,
            on_close,
            on_task_close,
            on_task_skip,
        } = builder;

        // Create the span
        let span = match parent_span_ref.level {
            SpanLevel::Info => {
                create_info_span_with_parent(Some(managed_parent_id.clone()), attributes)
            }
            SpanLevel::Debug => {
                create_debug_span_with_parent(Some(managed_parent_id.clone()), attributes)
            }
        };

        let new_managed = ManagedParentSpan::new(
            span,
            Some(managed_parent_id.clone()),
            parent_span_ref.span_key.clone(),
            on_close,
            on_task_close,
            on_task_skip,
        );

        let new_span_id = new_managed.span_id.clone();

        // Find the parent span and add this span as its child
        self.parent_spans
            .get_sync(&managed_parent_id)
            .expect("Parent etry must already be created")
            .get_mut()
            .children
            .insert(new_span_id.clone());

        // Add reverse mapping from span key to span id
        self.parent_span_key_to_span_id
            .insert_sync(parent_span_ref.span_key, new_span_id.clone())
            .map_err(|(key, id)| {
                fs_err!(
                    ErrorCode::Unexpected,
                    "Parent span key `{}` already mapped to a span id: {:?}",
                    key.as_str(),
                    id
                )
            })?;

        // Insert the new span
        self.parent_spans
            .entry_sync(new_span_id.clone())
            .insert_entry(new_managed);

        Ok(new_span_id)
    }

    /// Gets or creates a task span from a span tree request.
    ///
    /// Processes parent and related span chains, creating spans lazily. Returns either
    /// the newly created task span or the current span if `request` is no-op.
    ///
    /// # Arguments
    /// - `request`: Span tree request specifying hierarchy by span keys
    ///
    /// # Returns
    /// - `Ok(Span)`: The task span
    /// - `Err`: If any span key in the request was not pre-registered
    pub fn get_task_span(&self, request: SpanTreeRequest<R, S>) -> FsResult<Span> {
        let Some(task_span_request) = request.task_span else {
            // use current span
            return Ok(Span::current());
        };

        // Process parent span chain
        let parent_id = if let Some(span_ref) = request.parent_span {
            self.ensure_span_exists(span_ref)?
        } else {
            self.span_manager_cur_span_id.clone()
        };

        // Process each related span chain and collect innermost span IDs
        let mut related_ids = Vec::new();
        for related_ref in request.related_spans.into_iter() {
            let span_id = self.ensure_span_exists(related_ref)?;
            related_ids.push(span_id);
        }

        // Create the task span
        let managed_task_span = task_span_request.into_managed(parent_id.clone(), related_ids);
        let managed_task_span_span_id = managed_task_span.span_id.clone();

        // Get the span to return
        let ret = managed_task_span.span.clone();

        // Store the managed task span using its SpanId as the key.
        // This is safe because we hold a reference to the Span in ManagedTaskSpan,
        // which prevents the SpanId from being recycled until we remove the entry.
        self.task_spans
            .insert_sync(managed_task_span_span_id.clone(), managed_task_span)
            .map_err(|(span_id, _)| format!("SpanId {:?}", span_id))
            .expect("Span has just been created, should not already exist (must be a bug in handling of task closures)");

        // Find the parent span and add this span as its child
        self.parent_spans
            .get_sync(&parent_id)
            .expect("Parent etry must already be created")
            .get_mut()
            .children
            .insert(managed_task_span_span_id);

        Ok(ret)
    }

    /// Handles task completion, invoking callbacks and cleaning up spans.
    ///
    /// MUST be called for each span obtained from `get_task_span` upon task
    /// graceful completion with result. Subsequent calls with the same span_id
    /// will be ignored.
    ///
    /// Triggers `on_close` callbacks for the task and all ancestor spans in parent and
    /// related chains. Removes task span from tracking and closes parent spans with no
    /// remaining children.
    ///
    /// Consumes the task span handle intentionally.
    /// If parent or related spans must end after this task span, callers must pass
    /// the last remaining task span handle to this method. If another clone remains
    /// alive after this call, tracing may still emit the task span end later than
    /// its parent/related spans.
    ///
    /// # Arguments
    /// - `task_span`: span handle of the task span from `get_task_span`
    /// - `result`: Task result passed to `on_close` callbacks
    pub fn handle_task_finished(&self, task_span: Span, result: &R) {
        let Some(task_span_id) = task_span.id() else {
            // Task that didn't register a span (e.g., used current span) and that current span is disabled, nothing to do
            return;
        };
        let mut deferred_parent_spans = Vec::new();
        drop(task_span);

        {
            let Some((_, mut managed_task_span)) = self.task_spans.remove_sync(&task_span_id)
            else {
                // Task that didn't register a span (e.g., used current span), nothing to do
                return;
            };

            if let Some(on_close) = managed_task_span.on_close.take() {
                (on_close)(&managed_task_span.span, result);
            }

            let parent_id = managed_task_span.managed_parent_id.clone();
            let related_ids = managed_task_span.related_ids.clone();
            let task_span_id = managed_task_span.span_id.clone();

            // Update parent span chain
            self.update_parents(
                parent_id.clone(),
                task_span_id.clone(),
                &mut deferred_parent_spans,
                |ps| {
                    ps.on_task_close
                        .as_ref()
                        .is_none_or(|on_close| on_close(&ps.span, &managed_task_span.span, result))
                },
            );

            let mut seen_spans = HashSet::from([parent_id]);
            // Update each related span chain
            for related_id in related_ids {
                // Avoid updating the same span twice (in case of overlap with parent chain)
                if !seen_spans.insert(related_id.clone()) {
                    continue;
                }

                self.update_parents(
                    related_id,
                    task_span_id.clone(),
                    &mut deferred_parent_spans,
                    |ps| {
                        ps.on_task_close.as_ref().is_none_or(|on_close| {
                            on_close(&ps.span, &managed_task_span.span, result)
                        })
                    },
                );
            }
        }

        for parent_span in deferred_parent_spans {
            drop(parent_span);
        }
    }

    /// Handles task skip, invoking skip callbacks and cleaning up spans.
    ///
    /// MUST be called for each span obtained from `get_task_span` upon task
    /// skip. Subsequent calls with the same span_id will be ignored.
    ///
    /// Triggers `on_skip` callbacks for the task and all ancestor spans in parent and
    /// related chains. Removes task span from tracking and closes parent spans with no
    /// remaining children.
    ///
    /// Consumes the task span handle intentionally.
    /// If parent or related spans must end after this task span, callers must pass
    /// the last remaining task span handle to this method. If another clone remains
    /// alive after this call, tracing may still emit the task span end later than
    /// its parent/related spans.
    ///
    /// # Arguments
    /// - `task_span`: span handle of the task span from `get_task_span`
    /// - `skip_reason`: Reason passed to `on_skip` callbacks
    pub fn handle_task_skipped(&self, task_span: Span, skip_reason: &S) {
        let Some(task_span_id) = task_span.id() else {
            // Task that didn't register a span (e.g., used current span) and that current span is disabled, nothing to do
            return;
        };
        let mut deferred_parent_spans = Vec::new();
        drop(task_span);

        {
            let Some((_, mut managed_task_span)) = self.task_spans.remove_sync(&task_span_id)
            else {
                // Task that didn't register a span (e.g., used current span), nothing to do
                return;
            };

            if let Some(on_skip) = managed_task_span.on_skip.take() {
                (on_skip)(&managed_task_span.span, skip_reason);
            }

            let parent_id = managed_task_span.managed_parent_id.clone();
            let related_ids = managed_task_span.related_ids.clone();
            let task_span_id = managed_task_span.span_id.clone();

            // Update parent span chain
            self.update_parents(
                parent_id.clone(),
                task_span_id.clone(),
                &mut deferred_parent_spans,
                |ps| {
                    ps.on_task_skip.as_ref().is_none_or(|on_skip| {
                        on_skip(&ps.span, &managed_task_span.span, skip_reason)
                    })
                },
            );

            let mut seen_spans = HashSet::from([parent_id]);
            // Update each related span chain
            for related_id in related_ids {
                // Avoid updating the same span twice (in case of overlap with parent chain)
                if !seen_spans.insert(related_id.clone()) {
                    continue;
                }

                self.update_parents(
                    related_id,
                    task_span_id.clone(),
                    &mut deferred_parent_spans,
                    |ps| {
                        ps.on_task_skip.as_ref().is_none_or(|on_skip| {
                            on_skip(&ps.span, &managed_task_span.span, skip_reason)
                        })
                    },
                );
            }
        }

        for parent_span in deferred_parent_spans {
            drop(parent_span);
        }
    }

    fn update_parents(
        &self,
        mut parent_id: SpanId,
        mut cur_child_id: SpanId,
        deferred_parent_spans: &mut Vec<ManagedParentSpan<R, S>>,
        on_remove: impl Fn(&ManagedParentSpan<R, S>) -> bool,
    ) {
        while let Some((removed_parent_id, ps)) =
            self.parent_spans.remove_if_sync(&parent_id, |ps| {
                // Remove the child span from the parent's children
                ps.children.remove(&cur_child_id);

                // Invoke on remove callback, and get whether we can close this span as per callback.
                // Callback must be called regardless of whether we close the span or not.
                let can_close = on_remove(ps);

                // If no more children, we can close this span, i.e. drop it from manager.
                if ps.children.is_empty() && can_close {
                    // Invoke on close callback
                    if let Some(on_close) = ps.on_close.take() {
                        (on_close)(&ps.span);
                    }

                    // Trigger drop of the span by returning true
                    true
                } else {
                    // Keep the span in manager
                    false
                }
            })
        {
            // If we got here, it means we closed & removed some span. Meaning we need to
            // recursively remove it from the parent children as well.
            // Move up to the next parent
            cur_child_id = removed_parent_id;
            let managed_parent_id = ps.managed_parent_id.clone();
            deferred_parent_spans.push(ps);
            let Some(managed_parent_id) = managed_parent_id else {
                // Reached the root span, done
                break;
            };
            parent_id = managed_parent_id;
        }
    }
}

#[cfg(test)]
mod tests {
    use std::{
        collections::{HashMap, HashSet},
        sync::{Arc, Mutex},
    };

    use dbt_telemetry::GenericOpExecuted;
    use tracing::{Subscriber, span::Id as SpanId};
    use tracing_subscriber::{Layer, layer::Context, prelude::*};

    use super::*;

    #[derive(Clone, Default)]
    struct CloseRecorder {
        labels: Arc<Mutex<HashMap<SpanId, &'static str>>>,
        closed: Arc<Mutex<Vec<&'static str>>>,
    }

    impl CloseRecorder {
        fn label(&self, span_id: SpanId, label: &'static str) {
            self.labels
                .lock()
                .expect("lock should not be poisoned")
                .insert(span_id, label);
        }

        fn closed(&self) -> Vec<&'static str> {
            self.closed
                .lock()
                .expect("lock should not be poisoned")
                .clone()
        }
    }

    impl<S> Layer<S> for CloseRecorder
    where
        S: Subscriber,
    {
        fn on_close(&self, id: SpanId, _ctx: Context<'_, S>) {
            // `tracing` assigns opaque span IDs at creation time. The test labels
            // the IDs it cares about after creating each span, so the recorder can
            // ignore subscriber events for unrelated spans such as the test root.
            let label = self
                .labels
                .lock()
                .expect("lock should not be poisoned")
                .get(&id)
                .copied();

            if let Some(label) = label {
                self.closed
                    .lock()
                    .expect("lock should not be poisoned")
                    .push(label);
            }
        }
    }

    fn attrs(label: &str) -> TelemetryAttributes {
        GenericOpExecuted {
            operation_id: label.to_string(),
            display_action: label.to_string(),
            item_count_total: Some(1),
        }
        .into()
    }

    fn register_parent(
        span_manager: &SpanManager<(), ()>,
        key: &'static str,
        parent_key: Option<&'static str>,
    ) {
        span_manager
            .register_parent_span_builder(
                key.to_string(),
                parent_key.map(|key| ParentSpanRef::new(SpanLevel::Info, key.into())),
                Box::new(move || {
                    ParentSpanBuilder::new(
                        attrs(key),
                        None,
                        Some(Box::new(|_, _, _| true)),
                        Some(Box::new(|_, _, _| true)),
                    )
                }),
            )
            .expect("parent span builder should register");
    }

    fn label_parent(
        span_manager: &SpanManager<(), ()>,
        recorder: &CloseRecorder,
        key: &'static str,
    ) {
        let span_id = span_manager
            .parent_span_key_to_span_id
            .read_sync(&SpanKey::from(key), |_, span_id| span_id.clone())
            .expect("parent span should exist");

        recorder.label(span_id, key);
    }

    #[test]
    fn task_span_closes_before_removed_parent_and_related_span_chains() {
        let recorder = CloseRecorder::default();
        let subscriber = tracing_subscriber::registry().with(recorder.clone());

        tracing::subscriber::with_default(subscriber, || {
            // The span manager requires an active tracing span, and this root also
            // gives both synthetic managed trees a common ancestor.
            let root_span = tracing::info_span!("root");
            let _root_scope = root_span.enter();

            let span_manager = SpanManager::<(), ()>::new_empty();

            // Register the real parent chain for the task:
            //
            // actual_root
            //   actual_mid
            //     task
            //
            // Closing the only task should make `actual_mid` eligible to close,
            // then make `actual_root` eligible as the now-empty ancestor.
            register_parent(&span_manager, "actual_root", None);
            register_parent(&span_manager, "actual_mid", Some("actual_root"));

            // Register an independent related chain:
            //
            // related_root
            //   related_mid
            //     related_leaf
            //
            // The task follows from `related_leaf`. This 3-deep chain proves the
            // close-order fix is generic and walks direct related spans before
            // their ancestors, instead of only handling one parent level.
            register_parent(&span_manager, "related_root", None);
            register_parent(&span_manager, "related_mid", Some("related_root"));
            register_parent(&span_manager, "related_leaf", Some("related_mid"));

            // Build a task span under the innermost real parent and attach it to
            // the innermost related span. `get_task_span` lazily creates all
            // registered parents needed by this request.
            let mut builder = SpanTreeRequest::builder(SpanLevel::Info, attrs("task"), None, None);
            builder.with_parent(SpanLevel::Info, "actual_mid");
            builder.add_related_span(SpanLevel::Info, "related_leaf");

            let task_span = span_manager
                .get_task_span(builder.build())
                .expect("task span should be created");
            recorder.label(task_span.id().expect("task span should be enabled"), "task");

            // Parent IDs are only known after the task request has forced their
            // creation, so label them just before exercising the close path.
            for label in [
                "actual_root",
                "actual_mid",
                "related_root",
                "related_mid",
                "related_leaf",
            ] {
                label_parent(&span_manager, &recorder, label);
            }

            // This is the behavior under test: closing consumes the task span
            // handle. The manager must let that task span end before it drops any
            // parent or related span handles made eligible by callbacks.
            span_manager.handle_task_finished(task_span, &());
        });

        // Filter to the spans created for this scenario. The subscriber may also
        // close root/internal spans that are irrelevant to the ordering contract.
        let expected_labels = HashSet::from([
            "task",
            "actual_mid",
            "actual_root",
            "related_leaf",
            "related_mid",
            "related_root",
        ]);
        let actual = recorder
            .closed()
            .into_iter()
            .filter(|label| expected_labels.contains(label))
            .collect::<Vec<_>>();

        // The exact order documents the lifecycle contract:
        // 1. the task span closes first, before any parent/related span;
        // 2. the real parent chain closes child-to-ancestor;
        // 3. the related chain closes child-to-ancestor.
        //
        // If the task span handle is kept alive while parent callbacks remove
        // managed spans, this assertion fails with a parent/related close before
        // `task`, which is the telemetry bug this test guards against.
        assert_eq!(
            actual,
            vec![
                "task",
                "actual_mid",
                "actual_root",
                "related_leaf",
                "related_mid",
                "related_root",
            ]
        );
    }
}
