[graph]
exclude = ["dbt-fusion-workspace-hack"]

[bans]
multiple-versions = "allow"
deny = [
  { crate = "dbt-pretty-table", reason = "don't add more dependencies that include arrow in dbt-common" },
]
