// DO NOT EDIT!!!
// This file is generated by cargo run --bin adbc-sync

#[allow(clippy::type_complexity)]
#[rustfmt::skip]
pub static SORTED_CDN_DRIVER_CHECKSUMS: [(
    (
        &str, // backend
        &str, // target_os
        &str, // arch
        &str, // version
    ),
    &str, // checksum
); 211] = [
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.10"),
        "07c3a53a87d2304f37bcb5dedb9596432c5fed8e7f3403dfa9f1d5912e523aa8",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.11"),
        "f449484f8fea492855a2d2e8f49ed2b9701c675e6f125b6d54b7b29e1a5bd2fa",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.12"),
        "c408484d21dfcc76f3afbb0be80c353ad276ecebd98f2f66a6cbcf23dccbe6c0",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.13"),
        "7d188d408859741b3cf90dc01e77b2e969b0d98a3c21f83d59efad95df19c0b8",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.14"),
        "30caf0f89909ff1bc94a5c30ec4377ffbaed2f82b1c90b314be98688c51932b2",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.15"),
        "2567c010ce8dd660d61ca171ff6ade729dcbf1c71a66be58df7139ce8ff21a4b",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.8"),
        "b52f005523f09db5df8e59818f1775364d59086d96f42e0fe79b5a2d13f4d99b",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.9"),
        "ec2d400ed5cc868150aba4d2b995964cc821bb413d697f81bf5e2c358caca31e",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "ba4854112679eaff31303fbdb171827f500f7f9773973804136465ddd5d60507",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "beddb6cea5400630a188a87eb54a0b47d53d2ecf87fbf78c51300f75c6a4bf1a",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.12"),
        "dee60a0169296e524e4e476e27033bd5ef3e738da1f4564b4444b77d1bd4c8fd",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.13"),
        "d099d0e4e36963115ea9fe70b808014eb528bd71a023219240ce02c972f9b27c",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.14"),
        "8e50d0795e4fc4fdddee452c1356f7d213ba32dc1ad9955a746e0c6801a102cf",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.15"),
        "cdf41377abbc56f1c7d6efcd807b37b467c6823b79c1a138fd4305dfd0450fb9",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.8"),
        "346f3a916575f08bdba98d6dd6bc69df5d70d197e614cca25213ec839a4bb1b4",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.9"),
        "7015f7c515997ff666bbe3d96d62dd0da39824177dc9bc69155a989a500eed4d",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.10"),
        "16028dee53e2da1d4bf08b57b39a70ae5334f9923a68e9b047afbc22e7a46f6c",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.11"),
        "107d9dde4e6c081b908b3fa9eda0cc354a7da4a2f062879b91b8110971552fce",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.12"),
        "35d048f8211cbefab956fd677e2767895690881635014fe179ff8548dd95f333",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.13"),
        "ace49003e4e22ca2f65d3c6620464b0f8f8dee5fa035d5eb220de7010f2825ac",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.14"),
        "2da0327e7a3b6072b44df0e59bf7ad00bd61e26d4becd4e3296bb349f4c815a2",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.15"),
        "175d76d9b34bfdf4847fcd4f8eb590260cbf65fa9a09f0ae114a2eac182fa752",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.8"),
        "06723a3dc1ff519e952fb9844fd00ee75d414ca79da135207b96bbfd842cfabb",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.9"),
        "288009c1fd5c18ec9a54cfd7c7223179151d3fc57832f77d0c069220cbcc008b",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "1e0f6a2db045e217d42e52cc499df1422c81d49c37d7a64704665b4720d04cd0",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "e595ee7b4a84653a74af3a9747ef9f18cfa6c522d514bb10006827ec21ceecf7",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.12"),
        "9fa3d3a0abcf10cff2fe74bf9fe7e1c35ceda27e74fb08d74e52fc815a830383",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.13"),
        "9beec3a1c5ee20147b4511eab7ce787ddb861e540d3c82f900c6dfaa0c9b07a7",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.14"),
        "bc23ddaa0eaeb7dfa9144ab8aad657df64e935e12bb99c5d811f7b21ed411485",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.15"),
        "17740c39df7ff05f0851d19f80e591799f74780309715ecdac289208032bd27d",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.8"),
        "9d1ff67cde78b73bd5cc28b2f5ab4b853c3b4b598d99f7c9f1140b8111bf126b",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.9"),
        "36b9e54aa4ee5df0ebadb66f1635daa9736dc3173794762c09da401b5d9f177f",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "d9c7d501dc590dba12005972af1243797ee97fa717d1bcfe3e971397ed6f002b",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "421ab972c25d7b83bf0a09e0cfb5c91de01454bc7191219662c3dbbe3b876a5c",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.12"),
        "32bc018f9c823c9848a95a251e51d6a39996fb105a62f7a2d6790e51756233a0",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.13"),
        "cab55fdfc3a77fceabbd477b1f82975ab726c2eed8a102700b40a7efe37f56f0",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.14"),
        "0e215e67bb19710ab2b8fe1c5c9a824c6293198f3adfe0aa0ab2a08e1d98f3bd",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.15"),
        "15a7825c0c5c5dd13c5a817a6f5d527815a9b8aa2664c7f90a772a9598bdc671",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.8"),
        "ecf0127dfcc50f2917fbff4de9022f370b2f1caf44ab75ea01846d4a81990e60",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.9"),
        "4aaf192f26f791ab58850ff357235717245963e9e83401246ac72b54771517a3",
    ),
    (
        ("clickhouse", "apple-darwin", "aarch64", "0.1.0"),
        "0ccd62dbf47dc9714a328e70a1718faad4a188d222170849411829f2339bc5d2",
    ),
    (
        ("clickhouse", "apple-darwin", "aarch64", "0.1.0-alpha.1"),
        "d7f4dd2f67c4ba4e1569986d893ef9a877c3ae385da4ff3aa1faa646adb96f2a",
    ),
    (
        ("clickhouse", "apple-darwin", "aarch64", "0.1.0-alpha.2"),
        "7ba6156458599b35f6a1c5a2ddbc4cd62036c1d2e46abad702bb950478697472",
    ),
    (
        ("clickhouse", "manylinux_2_17-linux-gnu", "aarch64", "0.1.0"),
        "66050b3e1e945cdc9a8c6980e99396aea0592daf37d7e3d28f0ae4eeec2c8f2d",
    ),
    (
        ("clickhouse", "manylinux_2_17-linux-gnu", "aarch64", "0.1.0-alpha.1"),
        "5ea43a9ab39898fb448d23915cbea56c9284afea89d3324501606c3917d3fc37",
    ),
    (
        ("clickhouse", "manylinux_2_17-linux-gnu", "aarch64", "0.1.0-alpha.2"),
        "81cc15fea37bdf211f97be1eafd09d364d1772396a067f314ffbf01a943afec7",
    ),
    (
        ("clickhouse", "manylinux_2_17-linux-gnu", "x86_64", "0.1.0"),
        "6a6805df2b0ffed47beb2c78b4ddd6b2548fe100e42221c9bbcd0999fcae9bd4",
    ),
    (
        ("clickhouse", "manylinux_2_17-linux-gnu", "x86_64", "0.1.0-alpha.1"),
        "ef018d0c80498777583c92403781d8cda934aa5709dd27b624154f18d3891425",
    ),
    (
        ("clickhouse", "manylinux_2_17-linux-gnu", "x86_64", "0.1.0-alpha.2"),
        "d548d9e1e3511553f2e89fe66614e8cb4d69012f194491b869d31cbdbf19343f",
    ),
    (
        ("clickhouse", "pc-windows-msvc", "x86_64", "0.1.0"),
        "1f92179cc7f154de97edace0c5f1bad016f3dbd4b4b0c4a037401f84114309a7",
    ),
    (
        ("clickhouse", "pc-windows-msvc", "x86_64", "0.1.0-alpha.1"),
        "b29e3234db386be0c6e1cad6e4ea4185944dd063cb34d385b8ba3fca7b5451f2",
    ),
    (
        ("clickhouse", "pc-windows-msvc", "x86_64", "0.1.0-alpha.2"),
        "80a8eeabbb1a2913efc423c1bfddcd99bc5acffc19422181a9f7e8ddec54ed9b",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0+dbt0.21.6"),
        "56528db01bce2834d601acb45fe2b6f0ed1e80b7856078fb51f769c1459591ec",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0+dbt0.21.7"),
        "2aba2e95e2d5110f03bfbacd24a873ff94335f56e09e86ec04453151c499a1b6",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.10"),
        "cc2d50145a4420309c95a65a39b51dc2731279ffe1fa44898462aff7ceda8c3c",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.11"),
        "e9e15cc3dfb74683f753098d25a6e70bc0f5ecb8a4ca0a20ed0bc0db89935506",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0+dbt0.21.6"),
        "fcc269a403eb936bbf2a26936c7e7c61e8d05370cb087834838ab9eee6a380d4",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0+dbt0.21.7"),
        "fa06f6e8570f5b5ca65d1d653b157c9fbd8124fc8f3df1f9e1da1ab242deb33f",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "81c6d69d88cfb467c90aa9f16e65548f64ae4c10e8a5c23061a4e9dad9e84021",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "d83af05b478c6e3b0b945ac823bd0edd465a15091060df2f986969516bef9252",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.6"),
        "da993d20451662c41c21aea0b878b296532a30fe5d92db34f0ffc7179a6c369c",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.7"),
        "7cdccf45953ad72fc1285d286e52778ece6cb8949d56de43a418f59cde14d858",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.10"),
        "c8744e1a902357f49ee3ef21c6b366334a786af6394790751b0d5b9196857354",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.11"),
        "8d8bc2d435ea7384521c03fe563d46cc609070bae5dcbc090ef4142d2da2b9b7",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.6"),
        "37a4ba937d9aea99581ebca6b9e418121c4cc81e02f6273d7aa8022121d6854d",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.7"),
        "84e15ef3c5305431d34c84588aba10f4f68d8bbda2adcd157a2d18f39fe71434",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "24846db74ed1b4a9da2535b1215999f700668f8a5e9ccdb3a66ca6822f0175e9",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "50c20e05aedc0fe1cc9325f751953d307a1e743cbac334b27f19f96539e91ba3",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.6"),
        "e6ec384ae6a106208674f6aa3381baad64207c89da46560a6dfae5ec20d9b9cb",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.7"),
        "5d70ef5a470adf499e8aba40423123ce15df16c050012e16f1511c92091ec712",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "30fdb72ed127c68ec3bf9c0c411eb6e3fa847e670407004612d4c2efdefec37d",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "097926ba6db8df800159cef3ec845ac649d1bf34d8c8d420f6ec98c3022424a7",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.0.20"),
        "bf6a8920eccb15c8fc53902c52516bf3ef4a988129239e706631e0d59da22053",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "1.5.2"),
        "15a645873704bf5f610eb99cb2f3b8b725914f7172d7037b366e828bd6ae27a5",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "1.5.3"),
        "ac513a8baefc96218fdcdd2a02339e8eec259c44d54a2b2bd8163043262c80fa",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "1.5.4"),
        "0094c4c34218fad716c6d88409d78c90b10a1cbcdb16675989a5ba4db550c95d",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.0.20"),
        "ba1edff2728f0bd3b81b886baa8841af94a0186954bde69feab3138062f274b7",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "1.5.2"),
        "15a645873704bf5f610eb99cb2f3b8b725914f7172d7037b366e828bd6ae27a5",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "1.5.3"),
        "ac513a8baefc96218fdcdd2a02339e8eec259c44d54a2b2bd8163043262c80fa",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "1.5.4"),
        "0094c4c34218fad716c6d88409d78c90b10a1cbcdb16675989a5ba4db550c95d",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.0.20"),
        "14d8b6229614670c23cc6711532a22d76aea27b043e296f16c67fc412512fedd",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "1.5.2"),
        "061b4a6014a1456f3e3620328452af3cc687e0067a21d64d0f69dce023c14cce",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "1.5.3"),
        "789999e95798bc845d9948526bdd89ce432959c70702001a05c2aaee6e4b1b24",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "1.5.4"),
        "e50fe3e9c23766f6ccdfc3eb2ca2bf54da83cb639b6f3b3d100a9d83a7c604d9",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.0.20"),
        "8aad95227a05ecec119f76579625cc61eec52796a4a2e0be877e13b1a7933996",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "1.5.2"),
        "fc875898f6ce25aec77098a10e9160c536701932c7031e862dfcf5b435702852",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "1.5.3"),
        "5dc107adeb7d04ecf085da3d4f08244220ca2670235d66f39ffe80921130c5cb",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "1.5.4"),
        "23528e49435b97f2dfa924f5d19513849937e671bd392696ea26f3457f656556",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.0.20"),
        "bb36c1f5aeeeb676b722f7c7f5257998b53f113254c20e24937b102caafff658",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "1.5.2"),
        "8df3a965a573fe6fb33e123ae95ecbdf50122a322e968ec60b67f6fa9d182842",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "1.5.3"),
        "73b12943a85219ebc70da1f756fee0d33bbef0aac2a01ae4c6782b4e57f52deb",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "1.5.4"),
        "dd6a975796f513f1a52c0f99a0beecea227e3a4a546724ae63328cb58152aad9",
    ),
    (
        ("duckdb_extended", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.0.26"),
        "8ff984fa575a330e7d95e2950c8c06058b51488774526d49cddc6ca77a61e333",
    ),
    (
        ("duckdb_extended", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.0.27"),
        "1175f573e9a38dedcfb14b2c629a0a558a726720f3f38b464ecb8c74fc424c67",
    ),
    (
        ("duckdb_extended", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.0.28"),
        "48ee92e05c4f702fb07bebec3f2b1a468d9d30e02d9bea10bae717df75bdbd4b",
    ),
    (
        ("duckdb_extended", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.0.26"),
        "795c1625f8736cc9cb9122857b44bc8800436800835a64f1a1e7207e614e3806",
    ),
    (
        ("duckdb_extended", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.0.27"),
        "125e08ed1bd7310e4038b308809006d11c8c442e612db069865e1b6e2f6da6ed",
    ),
    (
        ("duckdb_extended", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.0.28"),
        "a58ae356b159d4c0e84a75365f716e81d1b1562ba66a11a554b4bf7ebc6f57a7",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.0.26"),
        "3f71ca8d73f2379505d25d40ed3e4200fe2eb4827a598cc3f2bb99ca21020931",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.0.27"),
        "66f8cd705f05695852982332bc8233cf8112b2214150fd54fc6f70ce4ba7281c",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.0.28"),
        "f68978ec0a45aae650aac66bd4a85897837ae124fc3b826c6009ac46955b66c0",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.0.26"),
        "5bd6e93cb9a783b5412bcec9b0e0289c1403377a7442ee553ad514654e2fc278",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.0.27"),
        "dae1405e9b5560a4a371667c3195cdaf25ae95856438697127235fff3a691606",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.0.28"),
        "7d769ea96c12d1c1c161953f07e7f6f68073dab56cc537b22db07b5a1ce6e0c2",
    ),
    (
        ("duckdb_extended", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.0.26"),
        "4dd8c879aabdc03949c24206e232dddf6ef0dcffce3d11a5b8a1fe32fdd8637f",
    ),
    (
        ("duckdb_extended", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.0.27"),
        "7e9ffc827d245141807e61ba95650b2d46e76662d31a86ab7d2d1a5d810eae6b",
    ),
    (
        ("duckdb_extended", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.0.28"),
        "9c7fc353caa4a99d8fc3c1a276300cc6a1a87fa15baa8c71c77b2c553b40fbb1",
    ),
    (
        ("mssql", "apple-darwin", "aarch64", "1.3.1"),
        "7e356f8f2f89a89b7a5c45fc255e8c5429f934b634e6071c689fad323a0f0de4",
    ),
    (
        ("mssql", "manylinux_2_17-linux-gnu", "aarch64", "1.3.1"),
        "cb3f81b8a220fb5659f1f9d3516b8cb15742326fb900df01b18cb68bb0dd0e96",
    ),
    (
        ("mssql", "manylinux_2_17-linux-gnu", "x86_64", "1.3.1"),
        "8714af2a435e4de896192fa89336dde1461ff127fd1375b07be33a8da4e7da30",
    ),
    (
        ("mssql", "pc-windows-msvc", "x86_64", "1.3.1"),
        "bcb6b0235297c0797e0cd0999fe1cf79d35c6b45e4abf33b9cae0252fc2a8cd3",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.18.0+dbt0.0.3"),
        "759eaacee1ea8139f884fa258ec8a7496ae9458f66cb8029817a2978b6f651ed",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.21.0+dbt0.21.0"),
        "07afc8277fd952d956b7de7a8129b323dad9a1aea71e35e3a0d31dee6371546d",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.18.0+dbt0.0.3"),
        "aa0b1da8145aa3b374dd0bd2b52cd02a8814ce3b03490aa8b5fc99178682803c",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.21.0+dbt0.21.0"),
        "cca3bb3f50a93879a346b50fb49374ced4494f65796ccd60e933c841eea3f27f",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.3"),
        "0650e5069c7ba4c545fc2850143109292842b117719991a7554bd35434a08bd0",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.0"),
        "279f5b9f042a7729f33c053e675f6d0c530a9ce8b88fa6965a981bd93a939df8",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.3"),
        "ff3cd85d65c0425eb31471f536812c333dec6ef0eb5e51d537ce607c9d2853dc",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.0"),
        "cbc2a0865bfc311663db2c2564830e4d4d260beda29baecd4371d8ce52eada5b",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.3"),
        "6f38377190af7320b0020c11f726e018cae0932272adba88359bf395c0f8ad94",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.0"),
        "4986f51e67888f77999525301386505f6375edcb36af4018becff374bb3f82e2",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.2"),
        "ab2b73c667a2b977362ca03cdca9ee309c68b1659f428dee176639d9070c9c1c",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.3"),
        "ce4f16d63e73955b7609ce3658fe95a14426ff0394305c1dcff060b5e71ce398",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.4"),
        "06577fa0d7049dbac38ad50c91c13c636f188d3278a2a3abc5ba563eb83d51f2",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.18.5"),
        "2543764be8c60f100a9a5252ea38839c8bb6c9a1bc4abd14ace05c83797fe77e",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.2"),
        "4283d97f8adaf6066ee84b9a3efb4ce4340774f8cd77e79310272daa317e9d7f",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.3"),
        "1be66c9643987b70b3baae8e41135415c4433d92e85508bec3c0a3c6e0151978",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.4"),
        "33f49abc1eaebead97d0e3edcfdfa37fb1c92b779bcfa5fee1022bb75ce1c9d4",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.18.5"),
        "6ca69cee28cfae0db39bc207c5d7ed20b040a3b35fdf7ef2fd962163be267e86",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.2"),
        "0ea7538a182b73bbafd4f594f8d63aa2cd26c3c2e354c13967540f861f20ccc7",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.3"),
        "cb2538c84e6dcbad15e074a2a9907a7cab551d66c833264a5af7835a19352cbd",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.4"),
        "4044e6e1f37ef4d5696c56b7de7303f8a56d64678609f2694413baf493cf9560",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.18.5"),
        "564194a3e7766ef2ac67c51325861399367aef1471d8741982f1a665f0080961",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.2"),
        "3c853f6444cd16bb9a7600f6b6350717aac440b840df1790d3c3d138d907283f",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.3"),
        "89c1e7b6b5e860259bb382d2b6257f9c593e8f977365f82dacc17bd14defb533",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.4"),
        "5a2600f85b0f9c8d34d91d8d0ae13cab266947238f97df07efe0351b53af3af9",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.18.5"),
        "0cc48ea7f6f39491750f47f4611ee3debfe8d2a7ed548dad10b6865bd4cfdb75",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.2"),
        "3c802b424c2fd1ea7fb45ebd1251fbe3e65b4d53a9d61dd4da303b1d5f206506",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.3"),
        "d6cf68f50f2551e07902d43631ff01f8dd507d9592a43cf8a074ac57ef2cb9e4",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.4"),
        "566dc019803edae2b29a58dace76034a793fd2ace289a54da35438834231e388",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.18.5"),
        "f47931677e3bd3ff10641f9d9ae0143dffefe5e148add30c7cbfd051e371477d",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.18.0+dbt0.0.4"),
        "d18e39ae09ff1a94da2dc3b4af9c7ac5f135d8affe8fab930d21966c6613b234",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.21.0+dbt0.21.1"),
        "a651b99de9f3d4987259735f9d4bd45c965edd76d46f7b8a1126e1ada07257ab",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.2"),
        "7398485ff259430a72b494a0748def1008b73b8f6f8f44a3f8e69e07e595f7e8",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.22.0"),
        "dd1eaf5090467e878316398381000d752a1e59d01856afef5ae516033b0ec73e",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.22.1"),
        "a1b67a3ed75972b231a2af4037e5d21565c821f728004cd9b7a45b63b3d8f166",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.18.0+dbt0.0.4"),
        "d0b94c4d28569cc95c0a07cb4218b053727ea9df13ed0ef2f55b3a920351d589",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.21.0+dbt0.21.1"),
        "06daae1581f75f8bf4d26fed1baf880d7ef31deeb0e15b5d6e90090e447831cc",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.2"),
        "9bea90938356fde1fd6f45328acc8d4195d65a99d5f0691a0589b22eefc6a5c4",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.22.0"),
        "9676f55baa15ee703447ae13f5e6afaaf2f45e6f59ccbb443b19452017e9d94d",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.22.1"),
        "a80cf5ea730bf9c7e437bd04f613b3bc17cca2b2e3b4c793e40ecf568f83305d",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.4"),
        "a826655fc9b626951d08c39b174756dff99b04b10c33601f9a1feff6325aec7a",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.1"),
        "c77793e9b83963d144a250bcec207dbec598b653eed077f4fae95e59959472c0",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.2"),
        "bc67fe4e18559d9cf32b7a70606062dde549048aeb3891043cfcc359beeeddf6",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.22.0"),
        "d45e958e253e1852ca116d20615889631ffb354c2c1d3b73ed74a30521795589",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.22.1"),
        "b9a9d02b194105aaa45e31e48b8da2331821dd3e22645fce740706655950cca5",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.4"),
        "a1eb2b25f4f4bf63c731fdc5d47bbca621e4bd23c6201b28d6f98ba85e400951",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.1"),
        "6833d78af651a22cd81e8e6b1a67cf5e263ff15cbf116a3292f5558f9cdad696",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.2"),
        "a4164521066952ea7e49429dec0ce416d28504085d1b136e7e1fdb52d1f80c4d",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.22.0"),
        "ecdaf290e104068013c8645578df0c548e1abe32370d03364f31d92accf29fb3",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.22.1"),
        "4d3e17a3afbffb4e22c193c254e5709d4c6006a17fb737ef94063aca4a0c9ec7",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.4"),
        "f73ad9a1bc6f6f418a9abb3ca54723da32f9b70e28b610d772aa796cc4d83641",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.1"),
        "4226fa0ed53848b61647f1bdf5b914bae7a033f44dc5bd84622f6d900c1f32f8",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.2"),
        "62266aef59e70e22ce293a6bc1accd24f09c0eb2283fb24c00bdf6e92213a28d",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.22.0"),
        "315a502177cd6dd0d9ca1d8bc8df44c545f6b1c7da4575300af94e7c4405d299",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.22.1"),
        "4f71b4f0ccdf5823a2fe70e0f8ccd76edcd3abbcae13bbe0fa92e0a8d529179d",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.10"),
        "499ca4757242586134dc5a09d07f6359dfd54ad637b20e497765042c71240708",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.11"),
        "988001635b63ffce5e7ebc5b78aeb4099c4a574a608972789a3a12cc11ec3f98",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.12"),
        "24fb799bcc1211668cdb832c09d3f8e4687f2f789b368f22abc17d7f520871bc",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.13"),
        "c45f3daa5132d929edbba3e1bdd925f21b485c4e3c0e826714d3fcd7bb74e510",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.14"),
        "892ecef4534a9b733b187511703128243ea392711042dff5ea25240f252b6c9f",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.15"),
        "8d9762600543ef7b7136cc00935e518cb750150c7491ee6cc56d894eaf4f7a5f",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "2373e633158e743e3df33ec7b79816f25c252be936e834a8e49400dd51c9f19e",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "61585acd8b80f3a808cffb1d030312ee995beacb86f9afcbae937ca4ba93d1e1",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.12"),
        "9100012d9dbf968e3346485bc8eb93b8308e174b9e8c0f2ed08a232b1269ae0a",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.13"),
        "889fb9b386b9875c9e54d06982bb475fc15c46ac413c9aa2d58e1711a933ae27",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.14"),
        "c206df97d94d84295c7713f49c48199301d20834489cb276b576d513864f80f4",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.15"),
        "e4b9107d787357c6720a3e1817d9fda9e3eb69d62b31e9339c85540174abb86b",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.10"),
        "a29e533233009fef21bccb93950b338e41806536d84ed5b6b42e657fcafb9999",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.11"),
        "725f717916e5baff2bb9068bc1e0b2b989ea344860bf355038c9a914d4d02ff8",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.12"),
        "38dddea25a7e4ead5d253cf491aebc8db7174bdcb5e2163bd67ae4a0ae426411",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.13"),
        "527a6d8ffc6e7ce2b922a49f21c646d713617f6b1c1bda799800ca9cc7d80407",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.14"),
        "34c1e80710ab2c7fd17a9c415452112341ce2e217bf2d5d1e4371d3860229111",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.15"),
        "9e203377486a63e74102208a3b273071c4c70c705534745bc63214cb79cde04e",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "60212a57ec83687b8db4e5aeddda59b4f472b97518ba34322c4d3e8e64d14172",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "cc4834689ab2ac2c02bcadee0346534d88e5e0e5e1f72a172935d074d17bc130",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.12"),
        "0672a665f36f262f8919554631465d25bdac5e2242f7053254708883013dc295",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.13"),
        "36099516357b357b6b6d07c03b6e6980425671b88b8319bf28e7da5e24df9df8",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.14"),
        "21b0a5e8896e4c4a80aa26822db4acaa7adfb4b7baaf767ac33ce87e8805784a",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.15"),
        "234da040cd3e3196df9a1ecdac7008c3414c1d2aa93682d3fd549be4bbe77048",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "896042c7f2d8ffc82093a79239a1adaa938e436952088fe369b86ccfdd04a79a",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "76a3263906d2d8c723b707584c3ac7de0d7e398d3fd25806e2b03a3541879ff3",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.12"),
        "6ebe6522377d8ebd9af59a51eab3a43fdf3e36c03aa4bf06ea17f914f7f99adc",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.13"),
        "06341a78ee31243b141405949c2d315506a5fc9401b4373f98c70fbefce406c2",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.14"),
        "0b969b0a2443ee52b5b982e2b98a8314a27871b0f0b762518f42585c65f54c73",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.15"),
        "3e8e36b57f6b613df6d6e7e7d1f7a0e886bbe43982b8301b8e97aa5cf0928900",
    ),
    (
        ("spark", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.1.0"),
        "b6c5434bea75b3a1da5d4f9598de93384d316c44e6fcd21d8b2dd8b3dfad93de",
    ),
    (
        ("spark", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.1.1"),
        "bae99943762c0a0ee9bc615b49aff22668ec5cb3d4f3447ebb738abda7d0f0e5",
    ),
    (
        ("spark", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.1.2"),
        "c67f0438c19ad463bc9eb0792f504fb14105e6470cde1974651ea30e08abfacb",
    ),
    (
        ("spark", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.1.0"),
        "347b18c1cc2fb82a22e3b51cb5d8f1165991cfc5eccf147f1baea3e1ddb7fb67",
    ),
    (
        ("spark", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.1.1"),
        "48298834a061ab3809189a6bbab828b502e0fcc3a3a836e90a27e3ed62a7c044",
    ),
    (
        ("spark", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.1.2"),
        "70a74705e224a1cd777fbd8453ee3ae631ff7c68bcbbd2a1282cacf49f8e29e6",
    ),
    (
        ("spark", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.1.0"),
        "b653fd0fe587e46f71375ce6927b81385c706dc80af98b9ab19b82799119f91b",
    ),
    (
        ("spark", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.1.1"),
        "7212f821c41131c9bd229875f3546e6a9da26f4a855faf18c8788a447de5b2fa",
    ),
    (
        ("spark", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.1.2"),
        "b75b2da9fad45d4762be3df198d647fa5cb268fe9197a0a5d6b8be4e9b429235",
    ),
    (
        ("spark", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.1.0"),
        "3712e4d8dd9938c22e070f66bafb7757e67ce8a29c13de57bf17c214013a13dc",
    ),
    (
        ("spark", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.1.1"),
        "09f3477242f0a1741954567b39e7bad1493e89b6c82b7f28e73ca2a88645745e",
    ),
    (
        ("spark", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.1.2"),
        "396d683d0db0dcd3f8a4eb72981663d32ed45e7d191b4db9f72a0c8615c65897",
    ),
    (
        ("spark", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.1.0"),
        "ee8d81104889a3e7a0324e108bc41a0a38e724806b92136e2c38f96e5ee7ca93",
    ),
    (
        ("spark", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.1.1"),
        "7530ed9212418205bfa5196b40541ccff8e83137852d2b3c732873abdea9e747",
    ),
    (
        ("spark", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.1.2"),
        "2c8185419f355e233fb77b68221bde0b361a5efe9d4bdb14198c56eb1c81aa07",
    ),
];
